"""added order column to house_members

Revision ID: 49541a1a96d5
Revises: add_chores_to_spaces
Create Date: 2026-01-29 10:31:03.837125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49541a1a96d5'
down_revision: Union[str, Sequence[str], None] = 'add_chores_to_spaces'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('house_members')
    op.drop_table('tasks')
    op.drop_table('spaces')
    op.drop_table('houses')
    op.drop_table('task_assignments')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('google_id', name=op.f('users_google_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('task_assignments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scheduled_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_assignments_task_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('task_assignments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('task_assignments_pkey'))
    )
    op.create_table('houses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('house_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('house_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('houses_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('houses_pkey')),
    sa.UniqueConstraint('house_key', name=op.f('houses_house_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('spaces',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('house_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('chores', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_spaces_house_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('spaces_pkey'))
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('house_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('space_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('repeat', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('tasks_created_by_fkey')),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('tasks_house_id_fkey')),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('tasks_space_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('tasks_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    op.create_table('house_members',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('house_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('house_members_house_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('house_members_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('house_members_pkey'))
    )
    # ### end Alembic commands ###
